rajanmaghera/riscv-analysis

- src/analysis/available.rs
- src/analysis/liveness.rs
- src/cfg/display.rs
- src/cfg/graph.rs
- src/cfg/node.rs
- src/gen/dead_code.rs
- src/gen/directions.rs
- src/gen/function_annotations.rs
- src/lints/checks.rs
- src/parser/parsing.rs
- src/passes/cfg_error.rs
Adds support for multiple return statements by remapping all other return statements to unconditional jumps to return blocks.
This was done for ease of implementation, so we don't have to introduce new blocks.
closes #13
> Support multiple returns

- .vscode/settings.json
- riscv_analysis/src/analysis/available.rs
- riscv_analysis/src/analysis/mod.rs
- riscv_analysis/src/analysis/set_traits.rs
- riscv_analysis/src/cfg/graph.rs
- riscv_analysis/src/cfg/node.rs
- riscv_analysis/src/fix/mod.rs
- riscv_analysis/src/lints/checks.rs
- riscv_analysis/src/parser/mod.rs
- riscv_analysis/src/parser/parsing.rs
- riscv_analysis/src/parser/token.rs
- riscv_analysis/src/passes/diagnostics.rs
This PR fixes the `cargo clippy` lint errors that exist in the main branch. With these changes, we would have a cleaner slate for the other PRs we want to merge in.
> [RV-11] chore: fix remaining clippy lints

- riscv_analysis/src/analysis/available.rs
- riscv_analysis/src/analysis/liveness.rs
- riscv_analysis/src/cfg/display.rs
- riscv_analysis/src/cfg/function.rs
- riscv_analysis/src/cfg/graph.rs
- riscv_analysis/src/cfg/node.rs
- riscv_analysis/src/cfg/test_wrapper.rs
- riscv_analysis/src/gen/dead_code.rs
- riscv_analysis/src/gen/directions.rs
- riscv_analysis/src/gen/ecall_terminate.rs
- riscv_analysis/src/gen/function_annotations.rs
- riscv_analysis/src/lints/checks.rs
- riscv_analysis/src/passes/cfg_error.rs
- riscv_analysis/src/passes/manager.rs
- riscv_analysis/src/passes/pass.rs
- riscv_analysis_cli/src/main.rs
Summary: This PR renames all symbols that begin with `CFG` to `Cfg`. This is done for consistency.
Test plan: Since this is a variable renaming, this will not affect any of the tests or introduce any new code. Existing tests should pass normally
> [RV-16] refactor: rename all usages of CFG to Cfg

- build-vsix.sh
- lsp/client/package-lock.json
- lsp/client/package.json
- lsp/server/package-lock.json
- lsp/server/package.json
**Summary**: This PR fixes an issue with building the VSCode extension due to a missing dependency.
**Test plan**: N/A as VSCode extension testing is not in our current scope.
> fix: VSCode extension build fails due to missing dependency

- riscv_analysis/src/parser/lexer.rs
- riscv_analysis/src/parser/parsing.rs
- riscv_analysis/src/parser/token.rs
Summary: This PR adds tokens for comments. The tokens contain the text of the comments, which can be used to annotate the output of the RISC-V analyzer in the future.
Test plan: 3 unit tests were added for tokenizing comments, including cases with the end of file and other tokens within comments. This is to ensure that tokenizing does not happen within comments.
> [RV-15] feat: add tokens for comment fields

- riscv_analysis/src/analysis/available.rs
- riscv_analysis/src/analysis/gen_kill.rs
- riscv_analysis/src/analysis/memory_location.rs
- riscv_analysis/src/analysis/mod.rs
- riscv_analysis/src/analysis/set_traits.rs
- riscv_analysis/src/cfg/display.rs
- riscv_analysis/src/cfg/node.rs
- riscv_analysis/src/cfg/test_wrapper.rs
- riscv_analysis/src/lints/checks.rs
- riscv_analysis_cli/resources/test/loop_check/raw.yaml
- riscv_analysis_cli/resources/test/treg/raw.yaml
**Summary**: This PR introduces a new type `MemoryLocation` as an abstract representation of memory. It currently has one variant `StackOffset`. This PR also replaces the use of raw `i32`s into this new type for better readability.
**Test plan**: `MemoryLocation` is currently only a wrapper type for `i32`, so it does not have any functionality. Thus, traditional tests should pass as they did before.
> [RV-19] refactor: use MemoryLocation over raw i32 to represent stack locations

- riscv_analysis/src/analysis/liveness.rs
- riscv_analysis/src/cfg/display.rs
- riscv_analysis/src/cfg/function.rs
- riscv_analysis/src/cfg/node.rs
- riscv_analysis/src/cfg/test_wrapper.rs
- riscv_analysis/src/fix/mod.rs
- riscv_analysis/src/gen/function_annotations.rs
- riscv_analysis/src/lints/checks.rs
- riscv_analysis/src/passes/cfg_error.rs
- riscv_analysis_cli/resources/test/loop_check/raw.yaml
- riscv_analysis_cli/resources/test/treg/raw.yaml
**Summary**: 
Change the function annotation pass to be top-down instead of bottom-up. Also allow an instruction to be part of more than one function.
**Test plan**:
The builtin CLI tests were modified slightly to allow for more than one function. When the parser is updated to allow string inputs, further tests will be added to the function annotation pass.
> [RV-2] Top down function pass

- riscv_analysis/src/parser/error.rs
- riscv_analysis/src/passes/cfg_error.rs
- riscv_analysis/src/passes/diagnostics.rs
- riscv_analysis/src/passes/lint_error.rs
- riscv_analysis_cli/src/main.rs
- riscv_analysis_lsp/src/lsp/mod.rs
**Summary**: 
Rename the lint type `WarningLevel` to `SeverityLevel` to match the LSP documentation. In the future, the Hint & Informations types will be added.
No functionality was changed.
> [RV-29] Rename WarningLevel to SeverityLevel

- riscv_analysis/src/passes/lint_error.rs
- riscv_analysis_cli/src/main.rs
- riscv_analysis_lsp/src/lsp/mod.rs
**Summary**: 
Add Information and hint levels to the lint severity levels.
The new levels are not used by any non-printing code.
> [RV-30] Add Information & Hint types to Severity Helper

- riscv_analysis/src/parser/empty_file_reader.rs
- riscv_analysis/src/parser/mod.rs
- riscv_analysis/src/parser/parsing.rs
- riscv_analysis/src/parser/register.rs
- riscv_analysis/src/parser/rv_string_parser.rs
- riscv_analysis/src/reader/mod.rs
- riscv_analysis_cli/src/main.rs
- riscv_analysis_lsp/src/lib.rs
- riscv_analysis_lsp/src/lsp/mod.rs
**Summary**: This PR introduces a new type and method `RVStringParser::parse_from_text(&str)` to generate parser nodes from raw text. Since the parsing is currently very coupled to reading files, due to the `.include` directive, these changes introduce a no-op reader `EmptyFileReader` to implement this without many changes to the underlying architecture. It still has room for a lot of improvements down the line.
**Test plan**: The new types include both doc-tests and traditional unit tests to test the basic functionality. All renaming changes don't have tests associated as they do not change any functionality.
> [RV-20] feat: add entry-point function for parsing a string into a list of `ParserNode`s

- riscv_analysis/src/parser/comments.rs
- riscv_analysis/src/parser/error.rs
- riscv_analysis/src/parser/lexer.rs
- riscv_analysis/src/parser/mod.rs
- riscv_analysis/src/parser/parsing.rs
**Summary**: This PR fixes 2 bugs; it prevents a token from being created across two lines, causing a panic when the column numbers were subtracted. In addition, it also fixes a bug where all comments were marked as unsupported operations.
**Test plan**: For bug 1, a `debug_assert!` was inserted to ensure that this case will never be available (in the future, I'd like to move this logic/design to the creation of a `Token`). For bug 2, a unit test was added.
> [RV-27] fix: comment tokens are incorrectly marked as an unsupported operation

- riscv_analysis/src/lints/mod.rs
- riscv_analysis/src/lints/overlapping_function.rs
- riscv_analysis/src/passes/cfg_error.rs
- riscv_analysis/src/passes/lint_error.rs
- riscv_analysis/src/passes/manager.rs
- riscv_analysis/src/passes/pass.rs
**Summary**: 
Detect instructions that belong to more than one function. Though this pattern is "technically correct" assembly, it doesn't generally occur in real assembly code. More likely, there is an erroneous jump to the middle of a function. Thus the user should be notified of any such occurrences.
Unit tests have been added.
> [RV-5] Detect Overlapping Function & Print a Warning

- riscv_analysis/src/lints/checks.rs
- riscv_analysis/src/lints/control_flow.rs
- riscv_analysis/src/lints/mod.rs
**Summary**: 
This PR fixes two issues:
- Previously, the `InvalidJumpToFunction` error was created for each function that a node was a part of. Now only a single instance is created.
- The `InvalidJumpToFunction` error was also created for overlapping functions. This functionality has been subsumed into the overlapping functions lint.
Added unit tests.
> [RV-40] Many invalid jump to bug

- riscv_analysis_cli/src/main.rs
**Summary**: 
Modify the error display function in the CLI such that it doesn't crash when the error's file is missing. This can occur for the `CfgError::UnexpectedError`. If such an error occurs, the display function now only prints the message.
No extra functionality was added.
> [RV-58] Modify cli to work for errors that have no file

- riscv_analysis/src/cfg/ops.rs
**Summary**: 
Change the results of division / remainder operations to be in line with the spec:
Added a test for the `div`, `divu`, `rem`, and `remu` operations.
> [RV-60] Fix MathOp to have the correct behaviour for division / remainder by 0

- riscv_analysis/src/parser/imm.rs
- riscv_analysis/src/parser/lexer.rs
- riscv_analysis/src/parser/parsing.rs
- riscv_analysis/src/parser/token.rs
**Summary**: 
RARS allows character literals to be used as immediates. Characters are treated as their corresponding integer. For example `li a0, 'a'` is equivalent to `li a0, 97`. In this PR, I add the following features:
- A new character token.
- The lexer produces character tokens for single characters (or escape codes) wrapped in single quotes.
- Character tokens are treated as integers by the parser.
Tests were added to the lexer, testing correct characters, un-closed characters, & invalid escape sequences.
> [RV-57] Handle character literals

- riscv_analysis/src/cfg/iterator.rs
**Summary**: 
The CFG iterator causes a subtraction underflow if the CFG has zero nodes. This is fixed by doing a check to see if the CFG is empty.
TODO
> [RV-59] Fix substraction underflow on empty CFG

- riscv_analysis_cli/Cargo.toml
- riscv_analysis_cli/src/lib.rs
- riscv_analysis_cli/src/printer.rs
- riscv_analysis_cli/tests/runner.rs
- riscv_analysis_cli/tests/sample/unused-value.json
- riscv_analysis_cli/tests/sample/unused-value.s
**Summary**: 
This PR adds the ability to run tests that take in an assembly file, run the linter, and compare the results with a file.
As we discover more issues, we can add representative tests with the correct outputs.
> [RV-64] Add a runner for CLI tests

- riscv_analysis/src/lints/checks.rs
- riscv_analysis_cli/tests/checks/no-invalid-assign-for-ret.json
- riscv_analysis_cli/tests/checks/no-invalid-assign-for-ret.s
- riscv_analysis_cli/tests/runner.rs
**Summary**: 
In [this](https://github.com/rajanmaghera/riscv-analysis/commit/88cf3239a01b4773958ab23ebd2da3b70d922d89#diff-e643315052a1817599e7cf60d2a086250156ac33cd2261b65b74d49e669c68f1L193) commit, `callee_saved()` was replaced with `saved()`, causing extra errors to be created for each `ret` instruction.
An integration test for this case was added.
> [RV-67] Fix bug causing "Invalid use before assignment" for ret instructions

- riscv_analysis/src/lints/callee_saved_garbage_read.rs
- riscv_analysis/src/lints/callee_saved_register.rs
- riscv_analysis/src/lints/control_flow.rs
- riscv_analysis/src/lints/dead_value.rs
- riscv_analysis/src/lints/ecall.rs
- riscv_analysis/src/lints/garbage_input_value.rs
- riscv_analysis/src/lints/instruction_in_text.rs
- riscv_analysis/src/lints/lost_callee_saved_register.rs
- riscv_analysis/src/lints/overlapping_function.rs
- riscv_analysis/src/lints/save_to_zero.rs
- riscv_analysis/src/lints/stack.rs
- riscv_analysis/src/passes/manager.rs
**Summary**: Use -Pass suffix on `LintPass` implementers.
To be merged in after #131 
**Test plan**: Refactor, previous tests should pass normally
> refactor: rename passes to -Pass
